
svn propset svn:mime-type text/plain ./doc/html/c_array_HTML.manifest
svn propset svn:eol-style native ./doc/html/c_array_HTML.manifest

svn propset svn:mime-type application/octet-stream  ./doc/src/images/alert.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/blank.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/1.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/10.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/11.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/12.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/13.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/14.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/15.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/2.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/3.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/4.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/5.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/6.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/7.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/8.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/callouts/9.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/caution.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/draft.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/home.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/important.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/next.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/next_disabled.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/note.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/prev.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/prev_disabled.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/smiley.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/tip.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/toc-blank.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/toc-minus.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/toc-plus.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/up.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/up_disabled.png
svn propset svn:mime-type application/octet-stream  ./doc/src/images/warning.png
